# Generated by Django 5.0.4 on 2024-05-07 07:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0010_alter_comment_author_alter_comment_news"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="rating",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Рейтинг",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="news.comment",
                verbose_name="Родительский комментарий",
            ),
        ),
    ]
