# Generated by Django 5.0.4 on 2024-05-10 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0012_remove_comment_rating_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="value",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name="Оценка"
            ),
        ),
    ]
