# Generated by Django 5.0.4 on 2024-05-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0013_alter_rating_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="value",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                null=True,
                verbose_name="Оценка",
            ),
        ),
    ]
